### ISSUE TITLE
Encoding failed: Handle passed to function call was invalid

### ISSUE THREAD

**Issue by 2e0wkw** [pschatzmann/arduino-audio-driver#18]
Hi, I am using the codec with Arduino Audio Tools on an Audio Kit board.

[E] AACEncoderFDK.h : 234 - Encoding failed: Handle passed to function call was invalid

I am using the streams-audiokit-webserver_aac.ino example.
I am also using the new Auduino-Audio-Driver.
I am also using the  auduino-fdk-acc codec

The code builds and uploads but i get this runtime error in the serial monitor when i connect to the web server via Chrome.

Thanks

Eric

**Comment by 2e0wkw** [comment]
Hi i am using the Audio Kit with ESP32 A1S. I have switched on logging and see that it related to a memory issue. I have read you blogs about Audio Kit and Arduino but i am still missing sone of the basic setup for using the board with arduino.

Thanks

**Comment by pschatzmann** [comment]
Could you please answer my questions: The core version you can see in the baord manager when you select ESP32 and the psram settings you can find in the Tools menu in Arduino

**Comment by 2e0wkw** [comment]
The board i select is the ESP32 Dev Board (i could not find one for A1S) and PSRAM is disabled at the moment

**Comment by pschatzmann** [comment]
I need the version number! 
Without this I will not be able to reproduce your result..

**Comment by 2e0wkw** [comment]
ah sorry my mistake 2.0.13

**Comment by pschatzmann** [comment]
I could not reproduce your error with [this example](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/streams-audiokit-webserver_aac/streams-audiokit-webserver_aac.ino)

**Comment by 2e0wkw** [comment]
Thanks fir trying Phil. To be honest i have just got it working by looking into all the things you asked me about. I think PSRAM was the main thing and updating the arduino/esp core to 2.0.14
